products = [
    {
        "id": 1,
        "symbol": "AAPL",
        "company_name": "Apple Inc.",
        "sector": "Technology",
        "exchange": "NASDAQ",
        "current_price": 212.45,
        "previous_close": 210.12,
        "day_high": 214.20,
        "day_low": 209.80,
        "volume": 65432100,
        "market_cap": 3200000000000,
        "pe_ratio": 34.5,
        "dividend_yield": 0.45,
        "description": "Designs and manufactures consumer electronics and software."
    },
    {
        "id": 2,
        "symbol": "MSFT",
        "company_name": "Microsoft Corporation",
        "sector": "Technology",
        "exchange": "NASDAQ",
        "current_price": 468.32,
        "previous_close": 465.10,
        "day_high": 470.00,
        "day_low": 462.70,
        "volume": 32145600,
        "market_cap": 3500000000000,
        "pe_ratio": 38.2,
        "dividend_yield": 0.68,
        "description": "Develops software, cloud, and enterprise services."
    },
    {
        "id": 3,
        "symbol": "GOOGL",
        "company_name": "Alphabet Inc.",
        "sector": "Communication Services",
        "exchange": "NASDAQ",
        "current_price": 189.76,
        "previous_close": 187.20,
        "day_high": 190.90,
        "day_low": 186.50,
        "volume": 28765400,
        "market_cap": 2400000000000,
        "pe_ratio": 26.8,
        "dividend_yield": 0.0,
        "description": "Parent company of Google and YouTube."
    },
    {
        "id": 4,
        "symbol": "AMZN",
        "company_name": "Amazon.com Inc.",
        "sector": "Consumer Discretionary",
        "exchange": "NASDAQ",
        "current_price": 228.94,
        "previous_close": 226.70,
        "day_high": 230.50,
        "day_low": 225.90,
        "volume": 41234500,
        "market_cap": 2500000000000,
        "pe_ratio": 49.1,
        "dividend_yield": 0.0,
        "description": "Global e-commerce and cloud computing company."
    },
    {
        "id": 5,
        "symbol": "TSLA",
        "company_name": "Tesla Inc.",
        "sector": "Automotive",
        "exchange": "NASDAQ",
        "current_price": 341.87,
        "previous_close": 336.20,
        "day_high": 345.00,
        "day_low": 334.10,
        "volume": 78456200,
        "market_cap": 1100000000000,
        "pe_ratio": 92.4,
        "dividend_yield": 0.0,
        "description": "Electric vehicles and clean energy company."
    },
    {
        "id": 6,
        "symbol": "NVDA",
        "company_name": "NVIDIA Corporation",
        "sector": "Semiconductors",
        "exchange": "NASDAQ",
        "current_price": 149.28,
        "previous_close": 147.30,
        "day_high": 150.20,
        "day_low": 146.90,
        "volume": 110234500,
        "market_cap": 3700000000000,
        "pe_ratio": 55.7,
        "dividend_yield": 0.03,
        "description": "Leader in GPUs and AI hardware."
    },
    {
        "id": 7,
        "symbol": "META",
        "company_name": "Meta Platforms Inc.",
        "sector": "Communication Services",
        "exchange": "NASDAQ",
        "current_price": 732.64,
        "previous_close": 725.90,
        "day_high": 735.80,
        "day_low": 721.50,
        "volume": 14567800,
        "market_cap": 1800000000000,
        "pe_ratio": 29.4,
        "dividend_yield": 0.27,
        "description": "Parent company of Facebook, Instagram, and WhatsApp."
    },
    {
        "id": 8,
        "symbol": "NFLX",
        "company_name": "Netflix Inc.",
        "sector": "Entertainment",
        "exchange": "NASDAQ",
        "current_price": 1235.48,
        "previous_close": 1222.60,
        "day_high": 1240.00,
        "day_low": 1218.20,
        "volume": 5234100,
        "market_cap": 520000000000,
        "pe_ratio": 58.3,
        "dividend_yield": 0.0,
        "description": "Global streaming entertainment service."
    },
    {
        "id": 9,
        "symbol": "JPM",
        "company_name": "JPMorgan Chase & Co.",
        "sector": "Financial Services",
        "exchange": "NYSE",
        "current_price": 297.55,
        "previous_close": 294.80,
        "day_high": 299.00,
        "day_low": 293.70,
        "volume": 8456200,
        "market_cap": 820000000000,
        "pe_ratio": 15.1,
        "dividend_yield": 1.9,
        "description": "Global banking and financial services company."
    },
    {
        "id": 10,
        "symbol": "RELIANCE",
        "company_name": "Reliance Industries Ltd.",
        "sector": "Conglomerate",
        "exchange": "NSE",
        "current_price": 1498.60,
        "previous_close": 1487.30,
        "day_high": 1505.00,
        "day_low": 1480.00,
        "volume": 9632100,
        "market_cap": 20200000000000,
        "pe_ratio": 28.6,
        "dividend_yield": 0.35,
        "description": "India's largest private sector company."
    }
]